version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres-payments
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments_db
    ports:
      - "5436:5432"
    volumes:
      - postgres_data_payments:/var/lib/postgresql/data
    networks:
      - usernet
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  transaction-service:
    build: .
    container_name: payments-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/payments_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8082:8082"
    networks:
      - usernet

networks:
  usernet:
    external: true

volumes:
  postgres_data_payments:
